name: "test"
on:
  pull_request:
  workflow_dispatch:
  
jobs:
  helm:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      
      - id: files
        uses: jitterbit/get-changed-files@v1
      
      - name: Get chart name
        id: chart_name
        run: |
          changed_charts=""
          for i in ${{ steps.files.outputs.all }}; do
            if echo $i|grep -q 'charts'; then
              unique_chart=$(cut -d '/' -f 2,3 <<< $i)
              if ! echo $changed_charts|grep -q $unique_chart; then
                changed_charts+="$unique_chart";
              fi
            fi
          done
          echo $changed_charts
          echo "::set-output name=CHANGED_CHART::$changed_charts"
      
      - name: Print changed_charts
        run: |
          echo "Files - ${{ steps.chart_name.outputs.CHANGED_CHART }}"
      - name: Read Helm Chart
        id: chart
        uses: jacobtomlinson/gha-read-helm-chart@master
        with:
          path: charts/${{ steps.chart_name.outputs.CHANGED_CHART }}
      - name: Print outputs
        run: |
          echo "Name - ${{ steps.chart.outputs.name }}"
          echo "Version - ${{ steps.chart.outputs.version }}"
          echo "App Version - ${{ steps.chart.outputs.appVersion }}"
          
      - name: Pr Includes File Change
        uses: Foodee/pr-includes-file-change@1.0.0
        with:
          paths: charts/${{ steps.chart_name.outputs.CHANGED_CHART }}/Chart.yaml
          
      - uses: ramonsnir/gh-action-pr-details@1.0.3
        id: vars
        with:
          repo-token: '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'

      - uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: PR

      - run: echo "PR ${prNumber} ${prTitle} at ${prUrl}"
        if: steps.PR.outcome == 'success'
        env:
          # JSON object with the full PR object
          # toJSON(fromJSON(...pr)) parses it into memory and then format is with pretty-print.
          prJSON: ${{ toJSON(fromJSON(steps.current_pr.outputs.pr)) }}
          # Direct access to common PR properties
          prNumber: ${{ steps.PR.outputs.number }}
          prUrl: ${{ steps.PR.outputs.pr_url }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBody: ${{ steps.PR.outputs.pr_body }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
          prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
          prLabel: ${{ steps.PR.outputs.pr_labels }}
